# Generated by Django 2.2.5 on 2020-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_auto_20200917_1739'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='users', to='pills.Pill'),
        ),
    ]
