# Generated by Django 2.2.5 on 2020-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pill_photos')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_serial_number', models.IntegerField(blank=True, null=True)),
                ('sortation', models.CharField(blank=True, max_length=50, null=True)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('mark_front', models.CharField(blank=True, max_length=10, null=True)),
                ('mark_back', models.CharField(blank=True, max_length=10, null=True)),
                ('shape', models.CharField(blank=True, max_length=10, null=True)),
                ('color_front', models.CharField(blank=True, max_length=10, null=True)),
                ('color_back', models.CharField(blank=True, max_length=10, null=True)),
                ('line_front', models.CharField(blank=True, max_length=10, null=True)),
                ('line_back', models.CharField(blank=True, max_length=10, null=True)),
                ('major_axis', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('minor_axis', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
