# Generated by Django 2.2.5 on 2020-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='dosage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='usage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
