# Generated by Django 2.2.5 on 2020-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0002_auto_20200921_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='mark_back',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='mark_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
