# Generated by Django 2.2.5 on 2020-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0003_auto_20200921_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='nature',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
