# Generated by Django 2.2.5 on 2020-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0004_auto_20200921_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='caution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='efficacy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='voulme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
