# Generated by Django 2.2.5 on 2020-09-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0004_auto_20200916_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='user',
        ),
    ]
