# Generated by Django 2.2.5 on 2020-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_auto_20200917_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='file',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='usage',
        ),
        migrations.AddField(
            model_name='pill',
            name='color_back',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='color_front',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='company_serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pill_photos'),
        ),
        migrations.AddField(
            model_name='pill',
            name='line_back',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='line_front',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='major_axis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='mark_back',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='mark_front',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='minor_axis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='pill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='pill_nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='pill_serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='shape',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='sortation',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
