# Generated by Django 2.2.5 on 2020-09-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_auto_20200926_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='cancel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='dur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='permission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='production_performance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
