# Generated by Django 2.2.5 on 2020-09-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0006_auto_20200917_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='pill_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='pill_nature',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='pill',
            old_name='pill_serial_number',
            new_name='serial_number',
        ),
        migrations.AlterField(
            model_name='pill',
            name='major_axis',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='minor_axis',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
