# Generated by Django 2.2.5 on 2020-10-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0007_pill_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='major_axis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='minor_axis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='thickness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
