# Generated by Django 2.2.5 on 2020-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0007_auto_20200917_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='image',
        ),
        migrations.AddField(
            model_name='pill',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='pill_photos'),
        ),
    ]
