# Generated by Django 2.2.5 on 2020-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0009_auto_20200917_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pill',
            name='sortation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
