# Generated by Django 2.2.5 on 2020-09-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pills.Pill')),
            ],
        ),
    ]
