# Generated by Django 2.2.5 on 2020-10-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='usage',
        ),
        migrations.AddField(
            model_name='schedule',
            name='dow',
            field=models.ManyToManyField(related_name='dayofweek', to='schedules.DayOfWeek'),
        ),
    ]
